### ISSUE TITLE
A typo? Or not?..

### ISSUE THREAD

**Issue by gabriel-fallen** [jonsterling/forest#2]
https://github.com/jonsterling/forest/blob/main/content/trees/tfmt-0007.md says:

> High-**equality** mathematical notes ...

(emphasis mine).

Should that be "high-quality"? If not, that's pretty funny, but the true meaning seems so deep I can't comprehend it as an outsider... 😅

Regardless, the notes are extremely interesting, thanks for all the efforts! 😃

**Comment by jonsterling** [comment]
Thank you very much, this is indeed a mistake :) And thanks for your kind words!

I’ll fix this when I return from my honeymoon, or would happily accept a pull request before then :)

**Comment by gabriel-fallen** [comment]
@jonsterling

> when I return from my honeymoon

Great to hear that, congratulations! I wish you both live happily ever after! ❤️ 😸
