### ISSUE TITLE
A place for discussions?

### ISSUE THREAD

**Issue by gabriel-fallen** [jonsterling/forest#3]
I'd like to comment on a phrase from the notes and maybe open a discussion therefore, but it's not necessarily an issue in a sense of a mistake. Thus I think Github Discussions would be a more suitable form. But if you don't want to bother and say opening an issue is fine, I'll do. 😸

**Comment by jonsterling** [comment]
@gabriel-fallen Thanks for the suggestion! GitHub Discussions is a very nice tool, but I think I don't have the energy to moderate a free-wheeling discussion forum at the moment (but this may change). On the other hand, would you mind emailing me about your thoughts?

**Comment by gabriel-fallen** [comment]
@jonsterling

> would you mind emailing me about your thoughts?

Will do. I'd emailed you in the first place, but I thought you might want a public record to point other people to the same answers. Sure thing you can decide on that and put it online later if it'll turn out worth the trouble.

**Comment by jonsterling** [comment]
Thanks, understood! I think that it will be most helpful if we first discuss and then synthesize what we learned — at that point, if it seems like it will be helpful, we could revise the existing trees or create new ones accordingly.

**Comment by jonsterling** [comment]
Understood, thanks! I think once we have discussed, we can synthesize 
that discussion into a revision or a new tree in the forest if it seems 
like what we came up with is helpful to other people.

Best,
Jon
